apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: roboshop

spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: roboshop

  template:
    metadata:
      labels:
        app: roboshop

    spec:
      containers:
        - name: nginx
          image: nginx:1.24

# change image tag version as 1.24 instead 1.27
# when we create a pod old pods will terminate and recreate a new pods, config propagate to container
